// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMQ9OW3LQfgTO3KE3rYp3Ty8pSc0brkJA',
    appId: '1:145545565413:web:b616d252da1437a5bdf00c',
    messagingSenderId: '145545565413',
    projectId: 'todo-e290d',
    authDomain: 'todo-e290d.firebaseapp.com',
    storageBucket: 'todo-e290d.appspot.com',
    measurementId: 'G-Y0M283HXVV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj8dlOz2WGXeTaa93o3kxn2XqVnbq-3tc',
    appId: '1:145545565413:android:fedab0d9b4f657d5bdf00c',
    messagingSenderId: '145545565413',
    projectId: 'todo-e290d',
    storageBucket: 'todo-e290d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq-0cmzg0AiIJaR2WCyAHOIzAubWL0Rko',
    appId: '1:145545565413:ios:65c15494f57aa462bdf00c',
    messagingSenderId: '145545565413',
    projectId: 'todo-e290d',
    storageBucket: 'todo-e290d.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq-0cmzg0AiIJaR2WCyAHOIzAubWL0Rko',
    appId: '1:145545565413:ios:b833527a76cceb41bdf00c',
    messagingSenderId: '145545565413',
    projectId: 'todo-e290d',
    storageBucket: 'todo-e290d.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
