// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6eVnUMKViy3VsuTfL3mCFVhCdCmoDavk',
    appId: '1:327182591960:web:9e7e2c9dd6c3504c0374ad',
    messagingSenderId: '327182591960',
    projectId: 'todo-697c7',
    authDomain: 'todo-697c7.firebaseapp.com',
    storageBucket: 'todo-697c7.appspot.com',
    measurementId: 'G-0MGX51CR4Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVaRojG_VWootwczQ8l_Qr1QJNYdNygQU',
    appId: '1:327182591960:android:1c490670f6336ae20374ad',
    messagingSenderId: '327182591960',
    projectId: 'todo-697c7',
    storageBucket: 'todo-697c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ-s20vO_xglzGvEMJFLtuXlfzHb6ZygY',
    appId: '1:327182591960:ios:e8a059535ceca8130374ad',
    messagingSenderId: '327182591960',
    projectId: 'todo-697c7',
    storageBucket: 'todo-697c7.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ-s20vO_xglzGvEMJFLtuXlfzHb6ZygY',
    appId: '1:327182591960:ios:e8a059535ceca8130374ad',
    messagingSenderId: '327182591960',
    projectId: 'todo-697c7',
    storageBucket: 'todo-697c7.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6eVnUMKViy3VsuTfL3mCFVhCdCmoDavk',
    appId: '1:327182591960:web:85abf46208c499520374ad',
    messagingSenderId: '327182591960',
    projectId: 'todo-697c7',
    authDomain: 'todo-697c7.firebaseapp.com',
    storageBucket: 'todo-697c7.appspot.com',
    measurementId: 'G-2NS9NP8RLJ',
  );

}